name: CI

on: [push]

jobs:
  build:

    runs-on: python:3.7-alpine
    
    steps:
    - uses: actions/checkout@v1
    - name: Install tox
      run: pip install tox
    - name: Run tox
      run: tox
